Models/ProductManagement.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace _71BootlegStore.Models
{
    public class ProductManagement
    {
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; }

        [StringLength(255)]
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Image")]
        [ValidateNever]
        public string? Image { get; set; }

		[Display(Name = "Quantity")]
		[Required]
		public int Quantity { get; set; }

		[Display(Name = "Gender")]
        [Required]
        public bool Gender { get; set; }

        [Display(Name = "Price")]
        [Required]
        public int Price { get; set; }

        [StringLength(255)]
        [Required]
        [Display(Name = "Color")]
        public string Color { get; set; }

        [StringLength(255)]
        [Required]
        [Display(Name = "Size")]
        public string Size { get; set; }

        [Display(Name = "Status")]
        public bool Status { get; set; } = true;

        [Display(Name = "CreatedAt")]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        [Display(Name = "UpdatedAt")]
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
    }
}

Controllers/ProductManagementController.cs
using _71BootlegStore.Data;
using _71BootlegStore.Models;
using _71BootlegStore.Repository.IRepository;
using _71BootlegStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _71BootlegStore.Controllers
{
    [Authorize]
    public class ProductManagementController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IFileUpload _fileUpload;

        public ProductManagementController(ApplicationDbContext Context, IFileUpload fileUpload)
        {
            _context = Context;
            _fileUpload = fileUpload;
        }
        public IActionResult Index()
        {
			ProductManagementVM productManagementVM = new()
			{
                ProductManagements = _context.ProductManagement.ToList()
			};

			return View(productManagementVM);
		}

        public async Task<IActionResult> Create(int id)
        {
            var productManagementVM = new ProductManagementVM();

            if (id == null || id == 0)
            {
                productManagementVM = new()
                {
                    Title = "New Product",
                    ProductManagement = new ProductManagement()
                };
            }
            else
            {
                var productManagement = await _context.ProductManagement.FindAsync(id);
                productManagementVM = new()
                {
                    Title = "Edit Product",
                    ProductManagement = productManagement
                };
            }

            return View(productManagementVM);
        }

        // Create
        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> Save(ProductManagement productManagement, int id, IFormFile? file, string Images)
        {
            if (productManagement != null)
            {
                var productInDb = await _context.ProductManagement.FindAsync(id);

                if (productInDb == null)
                {
                    if (file != null)
                    {
                        string Image = await _fileUpload.UploadFile(file, "Product", productManagement.Image);
                        productManagement.Image = Image;
                    }

                    await _context.ProductManagement.AddAsync(productManagement);
                    _context.SaveChanges();
                    TempData["success"] = "Created Product successfully";

                    return RedirectToAction("Index");
                }
                else
                {
                    try
                    {
                        if (file != null)
                        {
                            string Image = await _fileUpload.UploadFile(file, "Product", productManagement.Image);
                            productManagement.Image = Image;
                        }

                        productInDb.Name = productManagement.Name;
                        productInDb.Image = productManagement.Image;
                        productInDb.Quantity = productManagement.Quantity;
                        productInDb.Gender = productManagement.Gender;
                        productInDb.Price = productManagement.Price;
                        productInDb.Color = productManagement.Color;
                        productInDb.Size = productManagement.Size;
                        productInDb.Status = productManagement.Status;
                        productInDb.UpdatedAt = productManagement.UpdatedAt;
                        _context.ProductManagement.Update(productInDb);
                        _context.SaveChanges();
                        TempData["success"] = "Updated Product successfully";

                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        return BadRequest(ex);
                    }
                }
            }
            else
            {
                TempData["error"] = "Created error";
            }

            return BadRequest();
        }

        // delete item
        [HttpDelete]
        public async Task<IActionResult> DeleteItem(int id)
        {
            var returnMessage = "error";

            if (id != 0)
            {
                var productDb = _context.ProductManagement.FirstOrDefault(g => g.Id == id);

                if (productDb != null)
                {
                    await _fileUpload.Unlink(productDb.Image);
                    _context.ProductManagement.Remove(productDb);
                    _context.SaveChanges();

                    returnMessage = "success";
                    TempData["success"] = "Delete item successfully!";
                }
            }
            return Json(returnMessage);

        }
    }
}

Views/ProductManagement/Create.cshtml
@using _71BootlegStore.ViewModels
@model ProductManagementVM
@{
    ViewData["Title"] = "Product Management";
}

<div class="content">

    <h2 class="intro-y text-lg font-medium mt-10">
        Create Product
    </h2>

    <div class="intro-y mt-3">

        <form id="frmAuthUser" method="post" enctype="multipart/form-data">
            @* User Form *@
            <div class="intro-y box p-5 mt-5">
                <div class="border border-slate-200/60 rounded-md p-5">
                    <div class="font-medium text-base flex items-center border-b border-slate-200/60 pb-2">@Model.Title</div>

                    <div class="text-danger" asp-validation-summary="All"></div>
                    <input type="hidden" asp-for="@Model.Title">

                    <div class="col-span-12 mt-3">
                        <div class="form-inline grid grid-cols-12 gap-2">
                            <label asp-for="@Model.ProductManagement.Name"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ProductManagement.Name)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <input type="text" class="form-control" asp-for="@Model.ProductManagement.Name" required>
                                <span class="text-danger" asp-validation-for="@Model.ProductManagement.Name"></span>
                            </div>

                            <label asp-for="@Model.ProductManagement.Image"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ProductManagement.Image)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <input name="file" type="file" class="form-control" asp-for="@Model.ProductManagement.Image">
                                <input type="text" class="form-control" asp-for="@Model.ProductManagement.Image" hidden>
                                <span class="text-danger" asp-validation-for="@Model.ProductManagement.Image"></span>
                            </div>

                            <label asp-for="@Model.ProductManagement.Quantity"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ProductManagement.Quantity)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <input type="text" class="form-control" asp-for="@Model.ProductManagement.Quantity" required>
                                <span class="text-danger" asp-validation-for="@Model.ProductManagement.Quantity"></span>
                            </div>

                            <label asp-for="@Model.ProductManagement.Gender"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ProductManagement.Gender)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <select class="form-select" asp-for="@Model.ProductManagement.Gender" required>
                                    <option value="true">ผู้ชาย</option>
                                    <option value="false">ผู้หญิง</option>
                                </select>
                                <span class="text-danger" asp-validation-for="@Model.ProductManagement.Gender"></span>
                            </div>

                            <label asp-for="@Model.ProductManagement.Price"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ProductManagement.Price)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <input type="text" class="form-control" asp-for="@Model.ProductManagement.Price" required>
                                <span class="text-danger" asp-validation-for="@Model.ProductManagement.Price"></span>
                            </div>

                            <label asp-for="@Model.ProductManagement.Color"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ProductManagement.Color)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <input type="text" class="form-control" asp-for="@Model.ProductManagement.Color" required>
                                <span class="text-danger" asp-validation-for="@Model.ProductManagement.Color"></span>
                            </div>

                            <label asp-for="@Model.ProductManagement.Size"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ProductManagement.Size)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <input type="text" class="form-control" asp-for="@Model.ProductManagement.Size" required>
                                <span class="text-danger" asp-validation-for="@Model.ProductManagement.Size"></span>
                            </div>

                            <label asp-for="@Model.ProductManagement.Status"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ProductManagement.Status)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <select class="form-select" asp-for="@Model.ProductManagement.Status" required>
                                    <option value="true" selected>Active</option>
                                    <option value="false">Inactive</option>
                                </select>
                                <span class="text-danger"></span>
                            </div>

                        </div>
                    </div>

                </div>
            </div>

            <input type="hidden">

            <div class="flex justify-center flex-col md:flex-row gap-2 mt-5">
                <a asp-controller="ProductManagement" asp-action="Index" class="btn border-slate-300 dark:border-darkmode-400 text-slate-500 w-full md:w-52">Cancel</a>
                <button type="submit" class="btn btn-primary w-full md:w-52">Save</button>
            </div>

        </form>

    </div>
</div>

@section Scripts
{
    <script>
        const breadcrumbs = [
            {
                "label": "Master Data",
                "url": "javascript:;"
            },
            {
                "label": "Authorize",
                "url": "javascript:;"
            },
            {
                "label": "Create",
                "url": "javascript:;"
            }
        ];
        activeMenu(breadcrumbs);

        $(document).ready(function () {
           
        });
    </script>
}

Views/ProductManagement/Index.cshtml
@using _71BootlegStore.ViewModels
@model ProductManagementVM

@{
    ViewData["Title"] = "Product Management";
}

<div class="content">

	<h2 class="intro-y text-lg font-medium mt-10">
		Product Management
	</h2>

	<div class="grid grid-cols-12 gap-6 mt-5">
		<div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
			<a asp-controller="ProductManagement" asp-action="Create" class="btn btn-primary shadow-md mr-2">
				Create Product
			</a>
		</div>

		<div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
			<div class="relative overflow-x-auto">
				<table id="dataTable" class="table table-report -mt-2">
					<thead>
						<tr>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.Id"></label>
							</th>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.Name"></label>
							</th>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.Image"></label>
							</th>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.Quantity"></label>
							</th>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.Gender"></label>
							</th>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.Price"></label>
							</th>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.Color"></label>
							</th>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.Size"></label>
							</th>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.Status"></label>
							</th>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.CreatedAt"></label>
							</th>
							<th class="whitespace-nowrap">
								<label asp-for="@Model.ProductManagement.UpdatedAt"></label>
							</th>
							<th class="text-center whitespace-nowrap">ACTION</th>
						</tr>
					</thead>
					<tbody>
						@{
							int key = 0;
						}
						@foreach (var productManagements in Model.ProductManagements)
						{
							key++;
							<tr class="intro-x h-16">
								<td class="whitespace-nowrap">@key</td>
								<td class="whitespace-nowrap">@productManagements.Name</td>
								<td class="whitespace-nowrap"><img alt="Midone - HTML Admin Template" data-action="zoom" src="@productManagements.Image" width="100" height="100" /></td>
								<td class="whitespace-nowrap">
									@if (@productManagements.Quantity <= 10)
									{
										<label class="text-danger">@productManagements.Quantity</label>
									}
									else
									{
										<label>@productManagements.Quantity</label>
									}
								</td>
								<td class="whitespace-nowrap">
									@if (productManagements.Gender)
									{
										<div>ผู้ชาย</div>
									}
									else
									{
										<div>ผู้หญิง</div>
									}
								</td>
								<td class="whitespace-nowrap">@productManagements.Price</td>
								<td class="whitespace-nowrap">@productManagements.Color</td>
								<td class="whitespace-nowrap">@productManagements.Size</td>

								<td class="whitespace-nowrap">
									@if (productManagements.Status)
									{
										<div class='flex items-center text-success'><i data-lucide='check-square' class='w-4 h-4 mr-2'></i>Active</div>
									}
									else
									{
										<div class='flex items-center text-danger'><i data-lucide='check-square' class='w-4 h-4 mr-2'></i>Inactive</div>
									}
								</td>
								<td class="whitespace-nowrap">@productManagements.CreatedAt.ToString("dd/MM/yyyy")</td>
								<td class="whitespace-nowrap">@productManagements.UpdatedAt.ToString("dd/MM/yyyy")</td>
								<td class="table-report__action w-56">
									<div class="flex justify-center items-center">
										<a class="flex items-center mr-3" asp-controller="ProductManagement" asp-action="Create" asp-route-id="@productManagements.Id">
											<i data-lucide="check-square" class="w-4 h-4 mr-1"></i> Edit
										</a>
										<a class="flex items-center text-danger js-delete" href="javascript:;" data-id="@productManagements.Id" data-batch="@productManagements.Image">
											<i data-lucide="trash-2" class="w-4 h-4 mr-1"></i>
											Delete
										</a>
									</div>
								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

@section Scripts
{
	<script>
		const breadcrumbs = [
			{
				"label": "Master Data",
				"url": "javascript:;"
			},
			{
				"label": "Product Management",
				"url": "javascript:;"
			}

		];
		activeMenu(breadcrumbs);

		$(document).ready(function () {
			$('#dataTable').DataTable();

			setTimeout(() => {
				window.location.reload();
			}, 100000);

			// delete datatable item
			$(document).on('click', '.js-delete', function () {
				let itemId = $(this).attr('data-id');
				let Image = $(this).attr('data-batch');
				Swal.fire({
					title: 'Are you sure?',
					text: "You want to remove this Image ",
					icon: 'warning',
					showCancelButton: true,
					confirmButtonColor: '#3085d6',
					cancelButtonColor: '#d33',
					confirmButtonText: 'Yes, delete it!'
				}).then((result) => {
					if (result.isConfirmed) {
						deleteItem(itemId)
					}
				})
			});
			function deleteItem(id) {
				$.ajax({
					type: "DELETE",
					url: "@Url.Action("DeleteItem")" + "/" + id,
					success: function (data) {
						if (data == 'success') {
							window.location.reload();
						}
					},
					error: function (error) {
					},
				});
			}

			// edit datatable item
			let itemId;
			var Images;
			$(document).on('click', '.js-edit', function () {
				itemId = $(this).attr('data-id');
				Images = $(this).attr('data-batch');
			});

			$('.saveEdit').on('click', function () {
				let formData = new FormData($('#frmData')[0]);
				formData.append('Image', Images);
				$.ajax({
					type: "POST",
					url: "@Url.Action("Save")" + "/" + itemId,
					data: formData,
					dataType: 'json',
					processData: false,
					contentType: false,
					success: function (response) {
						if (response == 'success') {
							window.location.reload();
						}
					},
					error: function (jqXHR, textStatus, errorThrown) {
						$('.field-validation-valid').text('');
						for (const key in jqXHR.responseJSON) {
							$('.field-validation-valid[data-valmsg-for="' + key + '"]').text(jqXHR.responseJSON[key][0]);
						}
					}
				});
			})

		});
	</script>
}