Controllers/AuthorizeController.cs
using _71BootlegStore.Data;
using _71BootlegStore.Models;
using _71BootlegStore.Repository.IRepository;
using _71BootlegStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace _71BootlegStore.Controllers
{
    [Authorize]
    public class AuthorizeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<Role> _roleManager;
        private readonly IQueryBuilder _queryBuilder;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public AuthorizeController(ApplicationDbContext dBContext,
            UserManager<ApplicationUser> userManager,
            RoleManager<Role> roleManager,
            IQueryBuilder queryBuilder,
            SignInManager<ApplicationUser> signin)
        {
            _context = dBContext;
            _userManager = userManager;
            _roleManager = roleManager;
            _queryBuilder = queryBuilder;
            _signInManager = signin;
        }
        public IActionResult Index()
        {
            var users = _queryBuilder.GetAuthUserList();

            return View(users);
        }

        public async Task<IActionResult> Create(string id)
        {
            var authUserVM = new AuthUserVM();

            if (string.IsNullOrEmpty(id))
            {
                authUserVM = new()
                {
                    Title = "New User",
                    ApplicationUser = new ApplicationUser(),
                    RoleList = _context.Roles.Select(r => new SelectListItem
                    {
                        Text = r.Name,
                        Value = r.Id
                    })
                };
            }
            else
            {
                var user = await _userManager.FindByIdAsync(id);
                authUserVM = new()
                {
                    Title = "Edit User",
                    ApplicationUser = user,
                    RoleList = _context.Roles.Select(r => new SelectListItem
                    {
                        Text = r.Name,
                        Value = r.Id
                    }),
                    RoleId = _queryBuilder.GetUserRole(user.Id).Id,
                };
            }

            return View(authUserVM);
        }

        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> UpSert(AuthUserVM authUserVM)
        {
            if (authUserVM.Password == authUserVM.ConfirmPassword)
            {
                var userInDb = new ApplicationUser();

                if (authUserVM.Title == "Edit User")
                {
                    userInDb = await _userManager.FindByIdAsync(authUserVM.ApplicationUser.Id);
                    if (authUserVM.Password == null)
                    {
                        ModelState.Remove("Password");
                        ModelState.Remove("ConfirmPassword");
                    }
                }
                try
                {
                    var result = new IdentityResult();
                    var roleresult = new IdentityResult();
                    var role = new Role();
                    var IsSuccessed = true;

                    if (authUserVM.Title == "New User")
                    {
                        var user = new ApplicationUser
                        {
                            UserName = authUserVM.ApplicationUser.UserName,
                            FirstName = authUserVM.ApplicationUser.FirstName,
                            LastName = authUserVM.ApplicationUser.LastName,
                            Email = authUserVM.ApplicationUser.Email,
                            IsActive = authUserVM.ApplicationUser.IsActive,
                            Address = authUserVM.ApplicationUser.Address,
                        };


                        result = await _userManager.CreateAsync(user, authUserVM.Password);

                        if (result.Succeeded)
                        {
                            role = await _roleManager.FindByIdAsync(authUserVM.RoleId);
                            if (role != null)
                            {
                                roleresult = await _userManager.AddToRoleAsync(user, role.Name);
                            }

                            var createdUser = await _userManager.FindByNameAsync(authUserVM.ApplicationUser.UserName);
                        }
                        else
                        {
                            IsSuccessed = false;
                        }
                    }
                    else
                    {
                        if (userInDb != null)
                        {
                            userInDb.UserName = authUserVM.ApplicationUser.UserName;
                            userInDb.FirstName = authUserVM.ApplicationUser.FirstName;
                            userInDb.LastName = authUserVM.ApplicationUser.LastName;
                            userInDb.Email = authUserVM.ApplicationUser.Email;
                            userInDb.IsActive = authUserVM.ApplicationUser.IsActive;
                            userInDb.Address = authUserVM.ApplicationUser.Address;

                            if (authUserVM.Password != null)
                                userInDb.PasswordHash = _userManager.PasswordHasher.HashPassword(userInDb, authUserVM.Password);
                        }
                        result = await _userManager.UpdateAsync(userInDb);

                        if (result.Succeeded)
                        {
                            role = await _roleManager.FindByIdAsync(authUserVM.RoleId);
                            if (role != null)
                            {
                                var currentRoles = await _userManager.GetRolesAsync(userInDb);
                                if (currentRoles.Count() > 0)
                                {
                                    await _userManager.RemoveFromRolesAsync(userInDb, currentRoles);
                                }

                                roleresult = await _userManager.AddToRoleAsync(userInDb, role.Name);
                            }
                        }
                        else
                        {
                            IsSuccessed = false;
                        }
                    }

                    if (!IsSuccessed)
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(error.Code, error.Description);
                        }

                        authUserVM.RoleList = _context.Roles.Select(r => new SelectListItem
                        {
                            Text = r.Name,
                            Value = r.Id
                        });

                        return View(authUserVM);
                    }

                    TempData["success"] = authUserVM.Title + " success";

                    return RedirectToAction("Index");

                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                }

                authUserVM.RoleList = _context.Roles.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Id
                });
            }
            else
            {
                ModelState.AddModelError("InvalidPassword", "Invalid password");
                TempData["error"] = "Invalid password";
            }
            return View(authUserVM);
        }

        [HttpDelete]
        public IActionResult Delete(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var authUser = _context.applicationUsers.FirstOrDefault(a => a.Id == id);
                if (authUser != null)
                {
                    _context.applicationUsers.Remove(authUser);
                    _context.SaveChanges();
                }
            }

            TempData["success"] = "Deleted user successfully.";
            return Json("delete success");
        }
    }
}

Views/Authorize/Create.cshtml
@using _71BootlegStore.ViewModels
@model AuthUserVM

@{
    ViewData["Title"] = "Auth User";
}

<style>
    .grid .active {
        background-color: aqua;
    }
</style>

<div class="content py-4">
    <div class="intro-y mt-3">

        <form id="frmAuthUser" method="post">
            @* User Form *@
            <div class="intro-y box p-5 mt-5">
                <div class="border border-slate-200/60 rounded-md p-5">
                    <div class="font-medium text-base flex items-center border-b border-slate-200/60 pb-2">@Model.Title</div>

                    <div class="text-danger" asp-validation-summary="All"></div>
                    <input type="hidden" asp-for="@Model.Title">

                    <div class="col-span-12 mt-3">
                        <div class="form-inline grid grid-cols-12 gap-2">
                            <label asp-for="@Model.ApplicationUser.Id" class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0 hidden"></label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4 hidden">
                                <input type="text" class="form-control" asp-for="@Model.ApplicationUser.Id" required>
                                <span class="text-danger" asp-validation-for="@Model.ApplicationUser.Id"></span>
                            </div>

                            <label asp-for="@Model.ApplicationUser.UserName"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ApplicationUser.UserName)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <input type="text" class="form-control" asp-for="@Model.ApplicationUser.UserName" required>
                                <span class="text-danger" asp-validation-for="@Model.ApplicationUser.UserName"></span>
                            </div>

                            <label asp-for="@Model.ApplicationUser.Email"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ApplicationUser.Email)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <input type="email" class="form-control" asp-for="@Model.ApplicationUser.Email" required>
                                <span class="text-danger" asp-validation-for="@Model.ApplicationUser.Email"></span>
                            </div>

                            <label asp-for="@Model.ApplicationUser.FirstName"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ApplicationUser.FirstName)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <input type="text" class="form-control" asp-for="@Model.ApplicationUser.FirstName" required>
                                <span class="text-danger" asp-validation-for="@Model.ApplicationUser.FirstName"></span>
                            </div>

                            <label asp-for="@Model.ApplicationUser.LastName"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ApplicationUser.LastName)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <input type="text" class="form-control" asp-for="@Model.ApplicationUser.LastName" required>
                                <span class="text-danger" asp-validation-for="@Model.ApplicationUser.LastName"></span>
                            </div>

                            <label asp-for="@Model.RoleId"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.RoleId)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <select class="form-select" asp-for="@Model.RoleId" asp-items="@Model.RoleList" required>
                                    <option value="">Select...</option>
                                </select>
                                <span class="text-danger" asp-validation-for="@Model.RoleId"></span>
                            </div>

                            <label asp-for="@Model.ApplicationUser.IsActive"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ApplicationUser.IsActive)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <select class="form-select" asp-for="@Model.ApplicationUser.IsActive" required>
                                    <option value="true" selected>Active</option>
                                    <option value="false">Inactive</option>
                                </select>
                                <span class="text-danger" asp-validation-for="@Model.ApplicationUser.IsActive"></span>
                            </div>

                            <div id="privatePassword" class="col-span-12">
                                <div class="form-inline grid grid-cols-12 gap-2">
                                    <label asp-for="@Model.Password"
                                           class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                        <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.Password)
                                    </label>
                                    <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                        <input type="password" class="form-control" asp-for="@Model.Password" autocomplete="new-password" aria-required="true">
                                        <span class="text-danger" asp-validation-for="@Model.Password"></span>
                                    </div>

                                    <label asp-for="@Model.ConfirmPassword"
                                           class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                        <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ConfirmPassword)
                                    </label>
                                    <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                        <input type="password" class="form-control" asp-for="@Model.ConfirmPassword" autocomplete="new-password" aria-required="true">
                                        <span class="text-danger" asp-validation-for="@Model.ConfirmPassword"></span>
                                    </div>

                                    <div class="col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2"></div>
                                    <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                        <div class="form-check">
                                            <div class="bordercolor">
                                                <input id="checkbox-switch-1" class="form-check-input" type="checkbox">
                                            </div>
                                            <label class="form-check-label" for="checkbox-switch-1">Show Password</label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <label asp-for="@Model.ApplicationUser.Address"
                                   class="form-label col-span-12 md:col-span-2 xl:col-span-2 2xl:col-span-2 mr-0">
                                <span class="text-danger mr-1">*</span>@Html.LabelFor(m => m.ApplicationUser.Address)
                            </label>
                            <div class="col-span-12 md:col-span-4 xl:col-span-4 2xl:col-span-4">
                                <textarea type="text" class="form-control" asp-for="@Model.ApplicationUser.Address" required></textarea>
                                <span class="text-danger" asp-validation-for="@Model.ApplicationUser.Address"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <input type="hidden">

            <div class="flex justify-center flex-col md:flex-row gap-2 mt-5">
                <a asp-area="WEB" asp-controller="Authorize" asp-action="Index"
                   class="btn border-slate-300 dark:border-darkmode-400 text-slate-500 w-full md:w-52">
                    Cancel
                </a>
                <button type="submit" class="btn btn-primary w-full md:w-52 submit">Save</button>
            </div>

        </form>

    </div>
</div>


@section Scripts
{
    <script>
        const breadcrumbs = [
            {
                "label": "Master Data",
                "url": "javascript:;"
            },
            {
                "label": "Authorize",
                "url": "javascript:;"
            }
        ];
        activeMenu(breadcrumbs);

        $(document).ready(function () {

            // toggle password
            $('#checkbox-switch-1').on('click', function () {
                if ($(this).is(':checked')) {
                    $('#Password').attr('type', 'text');
                    $('#ConfirmPassword').attr('type', 'text');
                } else {
                    $('#Password').attr('type', 'password');
                    $('#ConfirmPassword').attr('type', 'password');
                }
            });

            // toggle checkbox
            $('#all').on('change', function () {
                if ($(this).prop('checked')) {
                    $(this).closest('table').find('input:checkbox').prop('checked', true);
                } else {
                    $(this).closest('table').find('input:checkbox').prop('checked', false);
                }
            });
        });
    </script>
}

Views/Authorize/Index.cshtml
@model List<UserViewModel>
@{
    ViewData["Title"] = "Auth User";
}

<div class="content">
    <h2 class="intro-y text-lg font-medium mt-10">
        Authorize
    </h2>

    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">

            <a asp-controller="Authorize" asp-action="Create" class="btn btn-primary shadow-md mr-2">
                <i data-lucide="user-plus" class="block mx-auto mr-2"></i>
                New User
            </a>
        </div>

        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
            <table id="dataTable" class="table table-report">
                <thead>
                    <tr>
                        <th class="whitespace-nowrap">User Name</th>
                        <th class="whitespace-nowrap">Email</th>
                        <th class="whitespace-nowrap">First Name</th>
                        <th class="whitespace-nowrap">Last Name</th>
                        <th class="whitespace-nowrap">Role</th>
                        <th class="whitespace-nowrap">Status</th>
                        <th class="whitespace-nowrap text-center">ACTION</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model)
                    {
                        <tr class="intro-x h-16">
                            <td>@user.UserName</td>
                            <td>@user.Email</td>
                            <td>@user.FirstName</td>
                            <td>@user.LastName</td>
                            <td>@user.RoleName</td>
                            <td>
                                @if (user.IsActive)
                                {
                                    <div class='flex items-center text-success'><i data-lucide='check-square' class='w-4 h-4 mr-2'></i>Active</div>
                                }
                                else
                                {
                                    <div class='flex items-center text-danger'><i data-lucide='check-square' class='w-4 h-4 mr-2'></i>Inactive</div>
                                }
                            </td>
                            <td class="table-report__action w-56">
                                <div class="flex justify-center items-center">
                                    <a class="flex items-center mr-3" asp-controller="Authorize" asp-action="Create" asp-route-id="@user.Id">
                                        <i data-lucide="check-square" class="w-4 h-4 mr-1"></i> Edit
                                    </a>
                                    <a class="flex items-center text-danger js-delete" href="javascript:void(0);" data-id="@user.Id">
                                        <i data-lucide="trash-2" class="w-4 h-4 mr-1"></i> Delete
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section Scripts
{
    <script>
        const breadcrumbs = [
            {
                "label": "Master Data",
                "url": "javascript:;"
            },
            {
                "label": "Authorize",
                "url": "javascript:;"
            }
        ];
        activeMenu(breadcrumbs);

        $(document).ready(function () {
            $('#dataTable').DataTable();

            $(document).on('click', '.js-delete', function () {
                let userId = $(this).attr('data-id');
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You want to remove this user!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        deleteUser(userId);
                    }
                })

            });
            function deleteUser(userId) {
                $.ajax({
                    type: "DELETE",
                    url: "Authorize/Delete/" + userId,
                    success: function (data) {
                        window.location.reload();
                    },
                    error: function (error) {
                        console.log(eror);
                    }
                });
            }
        });
    </script>
}